services:
  php-apache:
    container_name: php-apache
    image: php-apache
    networks:
      - camagru
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - mailcatcher
    volumes:
      - app-volume:/var/www/html
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - camagru
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: on-failure

  mailcatcher:
    container_name: mailcatcher
    image: dockage/mailcatcher:0.9
    networks:
      - camagru
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: on-failure

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - camagru
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

volumes:
  app-volume:
    driver: local
  postgres-volume:
    driver: local

networks:
  camagru:
    driver: bridge
